### ISSUE TITLE
Sort out mathematic articles' names.

### ISSUE THREAD

**Issue by MirageInc** [wlibrarian/wlibrarian.github.io#10]
Currently the ARMs are named with a multitude of standards, sometimes called "Volume X", other times called "Adventures ... Mathematics: X", rarely with their proper name. Similarly, the "Introduction to: X" have a variety of names deviating from the proper standard.

Each ARM should be titled in the form "Adventures in Recreational Mathematics N: XYZ", where N is such that this is the Nth ARM and XYZ is the title of the article, listed in order as:
1. Tilings
2. Cellular Automata
3. Big-O Notation (or you-know-what)
4. Confessions of a Sequence Addict
5. Cantor's Attic
6. Mathematician's Adventures in Wonderland (this title may be changed, since I quite like the use of "numberland" potentially for a number-theoretic article)
7. TBC

Similarly, each IT should be titled "Introduction to: X", where X is the subject, to make it clear that these are a regular thing.

**Comment by octogenary** [comment]
I think that this has been fixed over several commits, with the exception of the “Introduction to” proposal; there's no need to change it to “Introduction to:” from “An introduction to”, since there is only one.
